# Generated by Django 2.1 on 2018-08-16 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_image_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='created',
        ),
    ]
